// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _03_WEB_beforetest.Data;

#nullable disable

namespace _03_WEB_beforetest.Migrations
{
    [DbContext(typeof(ComponentsDbContext))]
    [Migration("20240918100739_01Migration")]
    partial class _01Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_03_WEB_beforetest.Modules.Distributors", b =>
                {
                    b.Property<int>("DistributorsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributorsId"));

                    b.Property<string>("DistributorsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistributorsId");

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("_03_WEB_beforetest.Modules.PCComponents", b =>
                {
                    b.Property<string>("ComponentsName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComponentUsage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistributorsId")
                        .HasColumnType("int");

                    b.HasKey("ComponentsName");

                    b.HasIndex("DistributorsId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("_03_WEB_beforetest.Modules.PCComponents", b =>
                {
                    b.HasOne("_03_WEB_beforetest.Modules.Distributors", "Distributors")
                        .WithMany()
                        .HasForeignKey("DistributorsId");

                    b.Navigation("Distributors");
                });
#pragma warning restore 612, 618
        }
    }
}
